version: 2

models:
  - name: fact_orders
    description: Order-level fact table - one row per order
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_unique_id
        tests:
          - not_null
      - name: order_date
        tests:
          - not_null
      - name: total_order_value
        tests:
          - not_null

  - name: dim_customer
    description: One row per unique customer - uses customer_unique_id as key
    columns:
      - name: customer_key
        tests:
          - not_null
          - unique
      - name: customer_segment
        tests:
          - accepted_values:
              arguments:
                values: ["high_value", "mid_value", "low_value"]

  - name: dim_product
    columns:
      - name: product_key
        tests:
          - not_null
          - unique

  - name: fact_events
    columns:
      - name: event_date
        tests:
          - not_null
          - unique

  - name: fact_rfm
    description: Customer-level RFM segmentation table
    columns:
      - name: customer_unique_id
        tests:
          - not_null
          - unique
      - name: recency_days
        tests:
          - not_null
      - name: frequency
        tests:
          - not_null
      - name: monetary
        tests:
          - not_null
      - name: segment
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ["Champions", "Loyal", "Potential", "At Risk", "Lost"]

  - name: fact_order_item
    description: Item-level fact table. One row per product item within an order
    columns:
      - name: order_item_key
        description: Surrogate primary key to uniquely identifies every item row in this table
        tests:
          - not_null
          - unique
          
      - name: order_id
        tests:
          - not_null

      - name: order_item_id
        tests:
          - not_null

      - name: product_id
        tests:
          - not_null

      - name: seller_id
        tests:
          - not_null

      - name: price
        tests:
          - not_null

      - name: freight_value
        tests:
          - not_null

      - name: item_total_value
        tests:
          - not_null

      - name: category_english
        description: English product category name from dim_product

      - name: category_portuguese
        description: Portuguese product category name from dim_product

      - name: product_weight_g
        description: Product weight in grams. Used for freight analysis

      - name: product_photos_qty
        description: Number of product photos. Proxy for listing quality
